sudo: required
services:
  - docker

before_install:
  - docker build  -f Dockerfile.dev -t haribhandari/frontend-docker .

script:
  - docker run haribhandari/frontend-docker npm run test -- --coverage
